"use client";
import React from "react";

  function TermsAndConditionsPage() {
    return (
      <div className="h-screen overflow-y-auto">
        <div className="py-24 sm:py-32">
          <div className="max-w-4xl mx-auto px-6 text-center">
            <h2 className="text-base font-semibold leading-7 text-indigo-600">
              Terms & Conditions
            </h2>
            <p className="mt-2 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
              Please Review Our Terms Carefully
            </p>
          </div>
          <div className="max-w-4xl mx-auto mt-8 px-6 text-gray-700 text-lg">
            <p className="leading-8">
              This document is an electronic record in terms of the Information
              Technology Act, 2000, and rules thereunder, as applicable, and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </p>

            <p className="mt-4 leading-8">
              This document is published in accordance with the provisions of Rule
              3(1) of the Information Technology (Intermediaries Guidelines) Rules,
              2011, which require publishing the rules and regulations, privacy
              policy, and Terms of Use for access or usage of the domain name
              [tezcode.tech] (&quot;Website&quot;), including the related mobile site and
              mobile application (hereinafter referred to as &quot;Platform&quot;).
            </p>

            <p className="mt-4 leading-8">
              The Platform is owned by [tezcode.tech], a company incorporated
              under the Companies Act, 1956, with its registered office at [Examba, Chikodi, Karnataka]. For the purposes of these Terms of Use, wherever the context
              requires, &quot;you&quot;, &quot;your&quot; or &quot;user&quot; shall mean any natural or legal
              person who has agreed to become a user/buyer on the Platform.
            </p>

            <h3 className="mt-8 text-lg font-semibold text-gray-900">
              1. General Terms
            </h3>
            <p className="mt-4 leading-8">
              Accessing, browsing, or otherwise using the Platform indicates your
              agreement to all the terms and conditions under these Terms of Use. If
              you transact on the Platform, you shall be subject to the policies
              applicable to the Platform for such transactions. By mere use of the
              Platform, you shall be contracting with the Platform Owner, and these
              terms and conditions constitute your binding obligations with the
              Platform Owner.
            </p>

            <h3 className="mt-8 text-lg font-semibold text-gray-900">
              2. Information Accuracy
            </h3>
            <p className="mt-4 leading-8">
              You agree to provide true, accurate, and complete information during
              registration and shall be responsible for all actions under your
              registered account. Neither we nor any third parties provide any
              warranty as to the accuracy or suitability of the information
              provided.
            </p>

            <h3 className="mt-8 text-lg font-semibold text-gray-900">
              3. Intellectual Property
            </h3>
            <p className="mt-4 leading-8">
              The contents of the Platform and the Services are proprietary to us.
              Unauthorized use of the Platform or Services may lead to action
              against you as per these Terms of Use and applicable laws.
            </p>

            <h3 className="mt-8 text-lg font-semibold text-gray-900">
              4. Payments and Charges
            </h3>
            <p className="mt-4 leading-8">
              You agree to pay all charges associated with availing the Services.
              The Platform Owner reserves the right to update pricing and charges
              for its services as needed.
            </p>

            <h3 className="mt-8 text-lg font-semibold text-gray-900">
              5. Limitation of Liability
            </h3>
            <p className="mt-4 leading-8">
              In no event will the Platform Owner be liable for any indirect,
              consequential, incidental, special, or punitive damages, including
              without limitation damages for loss of profits, business interruption,
              or loss of data.
            </p>

            <h3 className="mt-8 text-lg font-semibold text-gray-900">
              6. Governing Law and Jurisdiction
            </h3>
            <p className="mt-4 leading-8">
              These Terms and any dispute or claim relating to it shall be governed
              by the laws of India. All disputes shall be subject to the exclusive
              jurisdiction of the courts in [Chikodi, Karnataka].
            </p>

            <h3 className="mt-8 text-lg font-semibold text-gray-900">
              7. Force Majeure
            </h3>
            <p className="mt-4 leading-8">
              Neither party shall be liable for any failure to perform obligations
              due to unforeseen circumstances or causes beyond their reasonable
              control.
            </p>

            <p className="mt-8 text-sm leading-6 text-gray-600">
              For any concerns or communications relating to these Terms, please
              contact us using the information provided on this website.
            </p>
          </div>
        </div>
      </div>
    );
  }

export default TermsAndConditionsPage;
